services:
  # web:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
  #     - ..:/home/vscode/laravel
  #   depends_on:
  #     - laravel-todo-app

  laravel-app:
    image: mcr.microsoft.com/devcontainers/php:1-8.2-bullseye
    init: true
    ports:
      - 8080:8080
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ..:/home/vscode/laravel